# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1345142250);
user_pref("app.update.lastUpdateTime.background-update-timer", 1345142249);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1345142250);
user_pref("extensions.lastAppVersion", "2.0.0.18");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.identities", "id1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.accountmanager.accounts", "account1,account2");
user_pref("mail.accountmanager.defaultaccount", "account2");
user_pref("mail.accountmanager.localfoldersserver", "server1");
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.warn_on_send_accel_key", false);
user_pref("mail.identity.id1.draft_folder", "mailbox://reactos.dev@pop.gmail.com/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id1.fcc_folder", "mailbox://reactos.dev@pop.gmail.com/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id1.fullName", "Edijs Kolesnikovics");
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.stationery_folder", "mailbox://reactos.dev@pop.gmail.com/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "reactos.dev@gmail.com");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.root.none", "C:\\Documents and Settings\\Administrator\\Application Data\\Thunderbird\\Profiles\\ReactOS.default\\Mail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.root.pop3", "C:\\Documents and Settings\\Administrator\\Application Data\\Thunderbird\\Profiles\\ReactOS.default\\Mail");
user_pref("mail.root.pop3-rel", "[ProfD]Mail");
user_pref("mail.server.server1.directory", "C:\\Documents and Settings\\Administrator\\Application Data\\Thunderbird\\Profiles\\ReactOS.default\\Mail\\Local Folders");
user_pref("mail.server.server1.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server1.hostname", "Local Folders");
user_pref("mail.server.server1.name", "Local Folders");
user_pref("mail.server.server1.type", "none");
user_pref("mail.server.server1.userName", "nobody");
user_pref("mail.server.server2.directory", "C:\\Documents and Settings\\Administrator\\Application Data\\Thunderbird\\Profiles\\ReactOS.default\\Mail\\pop.gmail.com");
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/pop.gmail.com");
user_pref("mail.server.server2.download_on_biff", true);
user_pref("mail.server.server2.hostname", "pop.gmail.com");
user_pref("mail.server.server2.leave_on_server", true);
user_pref("mail.server.server2.login_at_startup", true);
user_pref("mail.server.server2.name", "Gmail - reactos.dev");
user_pref("mail.server.server2.port", 995);
user_pref("mail.server.server2.remember_password", true);
user_pref("mail.server.server2.socketType", 3);
user_pref("mail.server.server2.type", "pop3");
user_pref("mail.server.server2.userName", "reactos.dev");
user_pref("mail.shell.checkDefaultClient", false);
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.description", "Gmail");
user_pref("mail.smtpserver.smtp1.hostname", "smtp.gmail.com");
user_pref("mail.smtpserver.smtp1.port", 587);
user_pref("mail.smtpserver.smtp1.try_ssl", 2);
user_pref("mail.smtpserver.smtp1.username", "reactos.dev");
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.spam.version", 1);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "1.8.1.18");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("mailnews.ui.threadpane.version", 5);
